In [9]:
#numpy的相关操作
#array构建矩阵
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [11]:
a=np.array([1,2,2],dtype=np.int)
print(a.dtype)

int32


In [12]:
a=np.array([1,2,2],dtype=np.int64)
print(a.dtype)

int64


In [13]:
a=np.array([1,2,2],dtype=np.float)
print(a)
print(a.dtype)

[1. 2. 2.]
float64


In [14]:
a=np.array([[1,2,3],
            [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [16]:
#构建全为0的矩阵
a=np.zeros((3,4),dtype=np.int)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
#构建全为1的矩阵
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
#构建为空的矩阵
a=np.empty((3,4),dtype=np.float)
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
#arange类似于range,arange(起始值，终值，步长)，不包含终值
a=np.arange(10,20,2)
a

array([10, 12, 14, 16, 18])

In [22]:
a=np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
#linspace(起始值，终值，线段数),包含起始值和终值
a=np.linspace(1,12,5)
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [24]:
a=np.linspace(1,12,6).reshape((2,3))
a

array([[ 1. ,  3.2,  5.4],
       [ 7.6,  9.8, 12. ]])

In [36]:
#numpy的基础运算
a=np.arange(12).reshape((3,4))
b=np.array([1,2,2,5])
c=a+b
d=a-b
e=a*b
f=a**2  #**n表示n次方
g=np.array(100*np.sin(a),dtype=np.int)
print(a)
print(b)
# print(c)
# print(d)
# print(e)
# print(f)
# print(g)
print(a<4)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 2 2 5]
[[ True  True  True  True]
 [False False False False]
 [False False False False]]


In [38]:
#矩阵运算
a=np.array([[0,1],
            [1,2]])
b=np.arange(4).reshape((2,2))
c=np.dot(a,b) #dot表示矩阵相乘
print(a)
print(b)
print(c)

[[0 1]
 [1 2]]
[[0 1]
 [2 3]]
[[2 3]
 [4 7]]


In [45]:
#np.random.random（（m,n））表示构建m行n列的0-1的随机数矩阵
a=np.random.random((3,4))
print(a)
print(a.sum())    #等同于print(np.sum(a))
print(a.max())    #等同于print(np.max(a))
print(a.min())    #等同于print(np.min(a))
print(np.max(a,axis=0))     #axis=0表示列
print(np.max(a,axis=1))     #axis=1表示行

[[0.39346826 0.50506308 0.16008235 0.33697587]
 [0.90070261 0.46862757 0.21629691 0.14580195]
 [0.29519958 0.04952719 0.06590737 0.56498667]]
4.102639413913908
0.900702612504649
0.04952719218436574
[0.90070261 0.50506308 0.21629691 0.56498667]
[0.50506308 0.90070261 0.56498667]


In [61]:
a= np.arange(1,13).reshape((3,4))
print(a)
print(np.argmin(a))  #最小值的索引
print(np.argmax(a))  #最大值得索引
print(np.mean(a))    #矩阵的平均值
print(np.average(a)) #矩阵的平均值
print(np.cumsum(a))  #累积和
print(np.diff(a))    #后一个数减去前一个数
print(np.nonzero(a)) #非零数索引
print(np.sort(a))    #排序
print(a.T)           #转置矩阵
print(np.clip(a,5,9)) #小于5的数全为5，大于9的数全为9
print(np.mean(a,axis=0))  

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
0
11
6.5
6.5
[ 1  3  6 10 15 21 28 36 45 55 66 78]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int32), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int32))
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[5 5 5 5]
 [5 6 7 8]
 [9 9 9 9]]
[5. 6. 7. 8.]


In [63]:
#numpy的索引
#一维索引
a=np.arange(3,15)
print(a)
print(a[2])

[ 3  4  5  6  7  8  9 10 11 12 13 14]
5


In [67]:
#多维索引
a=np.arange(3,15).reshape((3,4))
print(a)
print(a[1,2])  #索引单个值
print(a[2])    #索引行
print(a[:,2])  #索引列

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
9
[11 12 13 14]
[ 5  9 13]


In [70]:
#for循环迭代矩阵获取*行*
a=np.arange(3,15).reshape((3,4))
print(a)
for row in a:  
    print(row)
for col in a.T:  #通过转置获取列
    print(col)   

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [72]:
#flatten()将矩阵变为1行m列列表
a=a=np.arange(3,15).reshape((3,4))
print(a)
print(a.flatten())
for i in a.flat:
    print(i)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [94]:
#arry合并
a=np.array([1,1,1])
b=np.array([2,2,2])
print(np.vstack((a,b,a,b)))  #vertical stack 垂直合并
print(np.hstack((a,b)))  #horizontal stack 水平合并
print(a[:,np.newaxis])    #在列上加一个维度
print(a[np.newaxis,:])    #在行上加一个维度
c=np.concatenate((a,b,a,b),axis=0)      #concatenate()可以在内部指定纵向或横向合并
print(c)

[[1 1 1]
 [2 2 2]
 [1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
[[1]
 [1]
 [1]]
[[1 1 1]]
[1 1 1 2 2 2 1 1 1 2 2 2]


In [103]:
#arry的分割
#split()只能相等分割
a=np.arange(12).reshape((3,4))
print(a)
print(np.split(a,3,axis=0))   #按行分成3块
print(np.split(a,2,axis=1))   #按列分成2块

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [104]:
#array_split()将矩阵不等分割
a=np.arange(12).reshape((3,4))
print(a)
print(np.array_split(a,2,axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [106]:
#vsplit()纵向分割
#hsplit()横向分割
a=np.arange(12).reshape((3,4))
print(np.hsplit(a,2))
print(np.vsplit(a,3))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [110]:
#arry的赋值
a=np.arange(12).reshape((3,4))
b=a
c=b
a[0,0]=100
print(a)
print(b)
print(c)
# b is a
c is a


[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


True

In [112]:
#copy()
a=np.arange(12).reshape((3,4))
b=np.copy(a)
# print(b)
a[0,0]=100
print(a)
print(b)


[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
